//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Affairs.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_Affairs
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "username")]
        public string UserName { get; set; }
        [Required]
        [Display(Name = "password")]
        public string Password { get; set; }
    }
}
